-- [FILE PATH]: schemas/gold/identity_map.sql
-- Patch #158
-- Execution Mode: Gold-Layer Identity Map DDL
-- Date: 2026-03-01

-- ============================================================
-- gold.te_identity_map
-- ============================================================
-- Purpose:
--   Canonical source-of-truth for te_party_pk assignment.
--   Every (te_source, source_id) pair maps 1-to-1 to a unique
--   te_party_pk BigInt, generated by the DB identity sequence.
--
-- Architecture:
--   PartyLinker reads/writes this table exclusively.
--   The generated te_party_pk is then used as the PK for
--   gold.te_party rows — this table is the authoritative sequence.
--
-- Zero-Hardcoding note:
--   This table stores no town-specific literals.  te_source
--   carries the town + system context (e.g. 'arlington-ma-tax-assessor').
-- ============================================================

CREATE TABLE IF NOT EXISTS gold.te_identity_map (

    -- Sequence-generated BigInt — the authoritative party PK
    te_party_pk BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    -- Originating system identifier (matches te_source on Gold records)
    te_source   VARCHAR(255) NOT NULL,

    -- Upstream system's native primary key for this record
    source_id   VARCHAR(255) NOT NULL,

    -- Audit timestamp — when this mapping was first created
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- Uniqueness constraint: one PK per (system, record) pair
    CONSTRAINT uq_identity_map_source_record
        UNIQUE (te_source, source_id)
);

-- ----------------------------------------------------------------
-- Index: supports the PartyLinker upsert CTE lookup path
-- ----------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_identity_map_lookup
    ON gold.te_identity_map (te_source, source_id);

-- schemas/gold/identity_map.sql
-- End of Patch #158
