# [FILE PATH]: core/expansion_agent.py
# Patch #175
# Execution Mode: Autonomous Expansion Engine
# Date: 2026-03-02
"""
TownEye UMF — Autonomous Expansion Engine
==========================================
Self-propagating onboarding system that scales the UMF to 500 towns by
combining an LLM (Gemini, OpenAI, or Anthropic) with config scaffolding.

Architecture
------------
Each iteration of the main loop:

  1. Reads the **expansion registry** (``configs/expansion_registry.json``) to
     know which towns are already onboarded.
  2. Sends the current seed list + already-onboarded list to the LLM and asks
     for the **next 10 adjacent / demographically similar municipalities** to
     onboard.  The LLM returns a structured JSON array — name, state, lat, lon,
     FIPS, population tier, and a one-line rationale.
  3. For each suggested town the engine:
        a. Derives a ``town_slug`` (``waltham-ma`` from ``"Waltham, MA"``).
        b. Calculates a precision-6 **geohash** from the LLM-supplied lat/lon.
        c. Scaffolds ``configs/{town_slug}/config.yaml`` from the master
           template, replacing all town-specific tokens.
        d. Appends the new slug to the registry.
  4. Prints a summary and offers to loop again (interactive mode) or exits
     (``--batch N`` mode).

Zero-Hardcoding contract
------------------------
* ``core/`` logic is entirely generic.  The template that gets stamped into
  each new town config lives in ``_CONFIG_TEMPLATE`` below — it is the only
  place where the config schema is defined.  To add a new config field to
  every onboarded town, add it once to the template.
* The engine never hard-codes any town's values.  All town-specific strings
  are injected from the LLM response JSON.

LLM providers (priority order when ``--provider`` is not specified)
-------------------------------------------------------------------
* **Gemini** — requires ``GEMINI_API_KEY`` env var.
  Uses ``gemini-2.5-flash`` by default.
* **OpenAI** — requires ``OPENAI_API_KEY`` env var.
  Uses ``gpt-4o-mini`` by default.
* **Anthropic** — requires ``ANTHROPIC_API_KEY`` env var.
  Uses ``claude-3-5-haiku-20250219`` by default.

Override with ``--provider gemini|openai|anthropic`` or set
``TOWNEYE_LLM_MODEL`` to override the model name.

Usage
-----
Interactive (ask for the next 10, then prompt to continue)::

    python core/expansion_agent.py

Batch — onboard the next N towns and exit::

    python core/expansion_agent.py --batch 50

Custom seed list with Gemini backend::

    python core/expansion_agent.py \\
        --seed "Cambridge MA,Medford MA,Malden MA" \\
        --provider gemini

Dry-run — print LLM suggestions without writing any files::

    python core/expansion_agent.py --dry-run

Full run to 500 towns::

    python core/expansion_agent.py --batch 500
"""

import argparse
import json
import logging
import os
import pathlib
import re
import sys
import textwrap
import time
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
_CONFIGS_DIR  = _PROJECT_ROOT / "configs"
_REGISTRY_PATH = _CONFIGS_DIR / "expansion_registry.json"

# ---------------------------------------------------------------------------
# LLM constants — all defaults can be overridden via TOWNEYE_LLM_MODEL
# ---------------------------------------------------------------------------
_OPENAI_DEFAULT_MODEL    = "gpt-4o-mini"
_ANTHROPIC_DEFAULT_MODEL = "claude-3-5-haiku-20250219"
_GEMINI_DEFAULT_MODEL    = "gemini-2.5-flash"
_LLM_TEMPERATURE         = 0.2   # low temperature for structured factual output
_LLM_MAX_TOKENS          = 2048

# ---------------------------------------------------------------------------
# Config template
# ---------------------------------------------------------------------------
# {tokens} are replaced by _scaffold_config().  All structural keys must
# remain generic — no town names or coordinates appear in core/ logic.
_CONFIG_TEMPLATE = """\
# configs/{town_slug}/config.yaml
# Auto-generated by TownEye UMF Expansion Engine (Patch #175)
# Seed: {seed_source}
# Generated: {generated_at}
#
# To onboard a further town, copy this file to configs/{{new-town-slug}}/config.yaml
# and update the values.  Zero changes to core/ are required.

town_slug: {town_slug}
town_name: {town_name}
state: {state}
county: {county}
fips_code: "{fips_code}"
population_tier: "{population_tier}"

# Geohash of the town centroid — precision 6 (~1.2 km cell).
# Computed from lat={lat}, lon={lon}
geo_hash: "{geo_hash}"

default_source: "{town_slug}-opengov"
version: "1.0.0"
updated_by: "UMF_System"
default_confidence: 1.0

# Expansion metadata — written by the Autonomous Expansion Engine.
expansion_metadata:
  onboarded_by: "expansion_agent"
  rationale: "{rationale}"
  lat: {lat}
  lon: {lon}
  llm_model: "{llm_model}"

source_mappings:
  census:           "census_api_2026"
  tax-assessor:     "{town_slug}-tax-assessor"
  permits:          "{town_slug}-permits"
  voters:           "{town_slug}-elections"
  property_tax:     "invoice-cloud"
  civic-meetings:   "{town_slug}-civic-meetings"
  community-events: "{town_slug}-community-events"
  311-seeclickfix:  "{town_slug}-311-seeclickfix"
  mbta-alerts:      "{town_slug}-mbta-alerts"
  school_calendar:  "{town_slug}-schools-ics"
  zoning_bylaws:    "{town_slug}-zoning-json"
  market_dynamics:  "mls-trends-bq"
  infra_friction:   "{town_slug}-dpw-capital-plans"
  connectivity:     "fcc-broadband-fabric"
  climate_resilience: "fema-flood-maps"
  social_equity:    "ej-burden-indices"

scraper_urls:
  property_assessor:   "https://PLACEHOLDER.patriotproperties.com/SearchResults.asp"
  civic_meetings:      "https://{town_slug_domain}/calendar/"
  community_events:    "https://{town_slug_domain}/events/"
  seeclickfix_311:     "https://seeclickfix.com/api/v2/issues"
  mbta_alerts:         "https://api-v3.mbta.com/alerts"
  school_calendar_ics: "https://PLACEHOLDER.{state_lower}.us/calendar/calendar.ics"
  zoning_bylaws_json:  "https://PLACEHOLDER.{state_lower}.us/zoning-bylaws.json"
  dpw_capital_plans_pdf: "https://PLACEHOLDER.{state_lower}.us/dpw-capital-plans.pdf"
  ejscreen_api:        "https://ejscreen.epa.gov/ArcGIS/rest/services/ejscreen/ejscreen_v2/MapServer/1/query"
  fema_nfhl_wfs:       "https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer/28/query"
  fcc_broadband_api:   "https://broadbandmap.fcc.gov/api/public/map/listAvailability"
  permits_api:         "https://PLACEHOLDER/api/v1/permits"

http:
  ssl_verify: true

scraper_column_map:
  source_id_col: "parcel_id"
  legal_name_col: "owner"
  data_table_idx:     1
  header_col_offset:  0
  source_id_col_idx:  0

scraper_search_params:
  SearchOwner: ""

scraper_page_param: "page"
scraper_max_pages: 5

party_type_org_keywords:
  - "LLC"
  - "LLP"
  - "INC"
  - "CORP"
  - "TRUST"
  - "TRS"
  - "TR"
  - "TRUS"
  - "REALTY"
  - "PROPERTIES"
  - "INVESTMENTS"
  - "ASSOCIATES"
  - "ASSOCIATION"
  - "NOMINEE"
  - "ESTATE"
  - "COMMISSION"
  - "BOARD"
  - "AUTHORITY"
  - "FOUNDATION"
  - "PARTNERS"
  - "GROUP"

town_pulse:
  civic_meetings:
    calendar_category: "Boards & Committees"
    lookahead_days: 90
  community_events:
    calendar_category: "Community Events"
    lookahead_days: 30
  seeclickfix:
    place_url: "{town_slug}"
    statuses:
      - "open"
      - "acknowledged"
      - "in_progress"
    per_page: 100
    event_type: "311_REQUEST"
  mbta:
    routes: []        # TODO: populate with MBTA routes serving this town
    activities:
      - "BOARD"
      - "EXIT"
      - "RIDE"
    api_key_env: "MBTA_API_KEY"
    event_type: "TRANSIT_ALERT"

market_dynamics:
  zip_codes: []       # TODO: populate with town zip codes
  geo_level: "ZIPCODE"
  metrics:
    MEDIAN_RENT_1BR:    {{baseline: 2000, monthly_drift: 0.005}}
    MEDIAN_RENT_2BR:    {{baseline: 2600, monthly_drift: 0.005}}
    MEDIAN_RENT_3BR:    {{baseline: 3200, monthly_drift: 0.004}}
    MEDIAN_SALE_PRICE:  {{baseline: 700000, monthly_drift: 0.003}}
    AVG_DAYS_ON_MARKET: {{baseline: 20, monthly_drift: -0.01}}
    MONTHS_OF_SUPPLY:   {{baseline: 1.5, monthly_drift: -0.02}}
    PRICE_PER_SQFT:     {{baseline: 500, monthly_drift: 0.004}}
  history_months: 12
  random_seed: 42

equity_census_tracts: []  # TODO: populate with Census GEOID tracts for this town
equity_indicators:
  CANCER_RISK_PERCENTILE:          {{mean: 42.0, std: 8.0}}
  PM25_PERCENTILE:                 {{mean: 50.0, std: 6.0}}
  LEAD_PAINT_PERCENTILE:           {{mean: 55.0, std: 10.0}}
  TRAFFIC_PROXIMITY_PERCENTILE:    {{mean: 60.0, std: 12.0}}
  SUPERFUND_PERCENTILE:            {{mean: 35.0, std: 9.0}}
  WASTEWATER_PERCENTILE:           {{mean: 40.0, std: 7.0}}
  LOW_INCOME_PERCENTILE:           {{mean: 35.0, std: 14.0}}
  LINGUISTIC_ISOLATION_PERCENTILE: {{mean: 18.0, std: 8.0}}
  LESS_HS_ED_PERCENTILE:           {{mean: 22.0, std: 9.0}}
  UNEMPLOYMENT_PERCENTILE:         {{mean: 31.0, std: 11.0}}
equity_disadvantaged_threshold: 65.0
equity_index_names:
  - "EPA_EJSCREEN"
equity_random_seed: 42

climate_flood_zone_map:
  "AE":       {{zone_type: "FLOOD_100YR",    risk_level: "HIGH"}}
  "AH":       {{zone_type: "FLOOD_100YR",    risk_level: "HIGH"}}
  "AO":       {{zone_type: "FLOOD_100YR",    risk_level: "HIGH"}}
  "A":        {{zone_type: "FLOOD_100YR",    risk_level: "HIGH"}}
  "VE":       {{zone_type: "FLOOD_100YR",    risk_level: "HIGH"}}
  "X":        {{zone_type: "FLOOD_500YR",    risk_level: "MODERATE"}}
  "FLOODWAY": {{zone_type: "FLOOD_FLOODWAY", risk_level: "HIGH"}}
  "D":        {{zone_type: "FLOOD_100YR",    risk_level: "UNDETERMINED"}}
  "OPEN_WATER": {{zone_type: "WETLAND",      risk_level: "LOW"}}

broadband_csv_column_map:
  provider_name: "brand_name"
  fcc_tech_code: "technology"
  max_down_mbps: "max_advertised_download_speed"
  max_up_mbps:   "max_advertised_upload_speed"
  geo_value:     "location_id"
  low_latency:   "low_latency"
  biz_res_code:  "business_residential_code"

broadband_tech_code_map:
  "10": "DSL"
  "40": "CABLE"
  "50": "FIBER"
  "60": "SATELLITE"
  "70": "FIXED_W"
  "30": "LTE"
  "31": "NR"
  "300": "OTHER"
"""

# ---------------------------------------------------------------------------
# LLM prompt
# ---------------------------------------------------------------------------
_SYSTEM_PROMPT = textwrap.dedent("""
    You are a municipal data expert helping TownEye expand its civic-intelligence
    platform to new towns across the United States.

    Your task: given a seed list of already-onboarded towns and a list of towns
    already suggested in previous rounds, propose the NEXT {n} municipalities to
    onboard.  Prioritise towns that are:
    - Geographically adjacent or within commuter distance of the seed towns
    - Demographically similar (comparable population, income, housing mix)
    - NOT already in the provided 'already_onboarded' list

    Return ONLY a JSON array (no markdown fences, no explanation) with exactly
    {n} objects.  Each object must have these fields — types shown:

    [
      {{
        "town_name":        "Waltham",           // string — proper name only, no state
        "state":            "MA",                // 2-letter USPS abbreviation
        "county":           "Middlesex County",  // full county name
        "fips_code":        "2507745000",        // 10-digit Census FIPS place code
        "lat":              42.3765,             // float, WGS-84, 4+ decimal places
        "lon":              -71.2356,            // float, WGS-84, 4+ decimal places
        "population_tier":  "25k-50k",           // one of: <10k|10k-25k|25k-50k|50k-100k|100k+
        "rationale":        "Shares commuter rail corridor with Lexington; high MLS volume"
      }},
      ...
    ]

    Return ONLY the JSON array.  No other text.
""").strip()

_USER_PROMPT_TEMPLATE = textwrap.dedent("""
    Seed towns already onboarded:
    {seed_list}

    Towns already suggested in previous expansion rounds (do NOT repeat):
    {already_onboarded}

    Please suggest the next {n} towns to onboard.
""").strip()


# ---------------------------------------------------------------------------
# Registry helpers
# ---------------------------------------------------------------------------

def _load_registry() -> Dict[str, Any]:
    """Load or initialise the expansion registry JSON."""
    if _REGISTRY_PATH.exists():
        with open(_REGISTRY_PATH) as f:
            return json.load(f)
    return {"onboarded": [], "rounds": []}


def _save_registry(registry: Dict[str, Any]) -> None:
    _REGISTRY_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(_REGISTRY_PATH, "w") as f:
        json.dump(registry, f, indent=2)


# ---------------------------------------------------------------------------
# Slug + geohash helpers
# ---------------------------------------------------------------------------

def _make_slug(town_name: str, state: str) -> str:
    """
    Derive a kebab-case ``town_slug`` from a town name and state abbreviation.

    Examples
    --------
    ``"Waltham", "MA"``  →  ``"waltham-ma"``
    ``"New Bedford", "MA"``  →  ``"new-bedford-ma"``
    """
    raw = f"{town_name} {state}".lower()
    slug = re.sub(r"[^a-z0-9]+", "-", raw).strip("-")
    return slug


def _compute_geohash(lat: float, lon: float, precision: int = 6) -> str:
    """
    Encode a WGS-84 lat/lon pair to a geohash string at *precision* characters.

    Falls back to a deterministic placeholder when ``geohash2`` is not installed
    so the engine stays runnable in environments that haven't yet pip-installed
    the library.
    """
    try:
        import geohash2  # type: ignore[import]
        return geohash2.encode(lat, lon, precision)
    except ImportError:
        logger.warning(
            "expansion_agent | 'geohash2' not installed — using placeholder hash. "
            "Run: pip install geohash2>=1.1"
        )
        # Deterministic fallback: encode lat/lon as base-36 digits
        raw = abs(int(lat * 1000)) + abs(int(lon * 1000))
        chars = "0123456789bcdefghjkmnpqrstuvwxyz"
        result = []
        for _ in range(precision):
            result.append(chars[raw % 32])
            raw //= 32
        return "".join(reversed(result))


# ---------------------------------------------------------------------------
# LLM client helpers — delegated to core.llm_client
# ---------------------------------------------------------------------------

def _select_llm_client() -> str:
    """
    Return the best available provider string based on set env vars.

    Priority: gemini > openai > anthropic.
    Raises ``RuntimeError`` if no key is found.
    """
    from core.llm_client import select_provider  # type: ignore[import]
    return select_provider()


def _ask_llm(
    seed_towns: List[str],
    already_onboarded: List[str],
    n: int = 10,
    provider: Optional[str] = None,
    model: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """
    Ask the LLM for the next *n* towns to onboard.

    Returns a list of parsed town dicts.  Raises ``ValueError`` if the LLM
    response cannot be parsed as a JSON array of the expected shape.
    """
    from core.llm_client import call_llm  # type: ignore[import]

    if provider is None:
        provider = _select_llm_client()

    if model is None:
        model = os.environ.get("TOWNEYE_LLM_MODEL") or None  # let call_llm pick the default

    system_prompt = _SYSTEM_PROMPT.replace("{n}", str(n))
    user_prompt = _USER_PROMPT_TEMPLATE.format(
        seed_list="\n".join(f"  - {t}" for t in seed_towns),
        already_onboarded=(
            "\n".join(f"  - {t}" for t in already_onboarded)
            if already_onboarded else "  (none yet)"
        ),
        n=n,
    )

    logger.info("expansion_agent | Querying %s for next %d towns ...", provider, n)
    t0 = time.perf_counter()

    raw = call_llm(
        system=system_prompt,
        user=user_prompt,
        provider=provider,
        model=model,
        n_tokens=_LLM_MAX_TOKENS,
    )

    elapsed = time.perf_counter() - t0
    logger.info("expansion_agent | LLM responded in %.2fs", elapsed)

    # Strip optional markdown fences the model sometimes adds despite instructions
    raw = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.IGNORECASE)
    raw = re.sub(r"\s*```$", "", raw)

    try:
        towns = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ValueError(
            f"expansion_agent | LLM returned non-JSON response: {exc}\n"
            f"Raw output (first 500 chars): {raw[:500]}"
        ) from exc

    if not isinstance(towns, list):
        raise ValueError(
            f"expansion_agent | Expected JSON array, got {type(towns).__name__}."
        )

    required_fields = {"town_name", "state", "lat", "lon"}
    for i, town in enumerate(towns):
        missing = required_fields - set(town.keys())
        if missing:
            raise ValueError(
                f"expansion_agent | Town #{i} missing required fields: {missing}. "
                f"Got: {list(town.keys())}"
            )

    return towns


# ---------------------------------------------------------------------------
# Config scaffolder
# ---------------------------------------------------------------------------

def _scaffold_config(
    town: Dict[str, Any],
    seed_source: str,
    llm_model: str,
    dry_run: bool = False,
) -> pathlib.Path:
    """
    Write ``configs/{town_slug}/config.yaml`` for a new town.

    Parameters
    ----------
    town : dict
        Parsed LLM town object with at minimum ``town_name``, ``state``,
        ``lat``, ``lon``.
    seed_source : str
        Human-readable label for the origin of this suggestion (e.g. the
        original seed list), written into ``expansion_metadata.rationale``.
    llm_model : str
        Model identifier stamped into ``expansion_metadata.llm_model``.
    dry_run : bool
        When True, print the config to stdout without writing any files.

    Returns
    -------
    pathlib.Path
        Path to the config file (written or would-be-written in dry_run mode).
    """
    town_name     = str(town.get("town_name", "Unknown")).strip()
    state         = str(town.get("state", "XX")).strip().upper()
    county        = str(town.get("county", "")).strip()
    fips_code     = str(town.get("fips_code", "")).strip()
    lat           = float(town.get("lat", 0.0))
    lon           = float(town.get("lon", 0.0))
    pop_tier      = str(town.get("population_tier", "unknown")).strip()
    rationale     = str(town.get("rationale", "")).replace('"', "'").strip()
    town_slug     = _make_slug(town_name, state)
    geo_hash      = _compute_geohash(lat, lon)

    # Derive a simple domain placeholder from slug (e.g. "waltham-ma.gov")
    town_slug_domain = f"{town_slug}.gov"

    generated_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    rendered = _CONFIG_TEMPLATE.format(
        town_slug=town_slug,
        town_name=town_name,
        state=state,
        state_lower=state.lower(),
        county=county,
        fips_code=fips_code,
        lat=lat,
        lon=lon,
        geo_hash=geo_hash,
        pop_tier=pop_tier,
        population_tier=pop_tier,
        rationale=rationale,
        llm_model=llm_model,
        seed_source=seed_source,
        generated_at=generated_at,
        town_slug_domain=town_slug_domain,
    )

    config_path = _CONFIGS_DIR / town_slug / "config.yaml"

    if dry_run:
        print(f"\n{'─'*60}")
        print(f"DRY-RUN | Would write: {config_path}")
        print(f"{'─'*60}")
        print(rendered[:800], "...(truncated)")
        return config_path

    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w") as f:
        f.write(rendered)

    logger.info("expansion_agent | Scaffolded → %s", config_path)
    return config_path


# ---------------------------------------------------------------------------
# Main expansion loop
# ---------------------------------------------------------------------------

def _onboarded_slugs(registry: Dict[str, Any]) -> List[str]:
    return [entry["town_slug"] for entry in registry.get("onboarded", [])]


def _onboarded_display_names(registry: Dict[str, Any]) -> List[str]:
    return [
        f"{e.get('town_name', '?')}, {e.get('state', '?')}"
        for e in registry.get("onboarded", [])
    ]


def run_expansion(
    seed_towns: List[str],
    batch_total: Optional[int] = None,
    per_round: int = 10,
    dry_run: bool = False,
    provider: Optional[str] = None,
    model: Optional[str] = None,
) -> None:
    """
    Main loop — keep asking the LLM for more towns until *batch_total* is
    reached (batch mode) or the user declines to continue (interactive mode).

    Parameters
    ----------
    seed_towns : list[str]
        Initial seed list, e.g. ``["Arlington, MA", "Lexington, MA"]``.
    batch_total : int, optional
        If set, run until this many NEW towns have been onboarded.  If None,
        runs one round then prompts to continue interactively.
    per_round : int
        Number of towns to request per LLM call (default 10).
    dry_run : bool
        Print scaffolded configs to stdout; do not write files.
    provider : str, optional
        ``"openai"`` or ``"anthropic"``.  Auto-detected when omitted.
    model : str, optional
        Override LLM model identifier.
    """
    registry = _load_registry()
    total_onboarded_this_session = 0

    # Resolve the effective provider without raising — we only need the key
    # to be present when an actual LLM call is made inside the loop.
    effective_provider = provider
    if effective_provider is None:
        if os.environ.get("GEMINI_API_KEY"):
            effective_provider = "gemini"
        elif os.environ.get("OPENAI_API_KEY"):
            effective_provider = "openai"
        elif os.environ.get("ANTHROPIC_API_KEY"):
            effective_provider = "anthropic"
        else:
            effective_provider = "gemini"   # will raise with a clear message at call-time

    _model_defaults = {
        "gemini":    _GEMINI_DEFAULT_MODEL,
        "openai":    _OPENAI_DEFAULT_MODEL,
        "anthropic": _ANTHROPIC_DEFAULT_MODEL,
    }
    effective_model = model or os.environ.get(
        "TOWNEYE_LLM_MODEL",
        _model_defaults.get(effective_provider, _OPENAI_DEFAULT_MODEL),
    )

    logger.info("expansion_agent | Starting expansion loop")
    logger.info("expansion_agent | Seed towns  : %s", seed_towns)
    logger.info("expansion_agent | Batch target: %s", batch_total or "interactive")
    logger.info("expansion_agent | Per-round   : %d", per_round)
    logger.info("expansion_agent | Dry run     : %s", dry_run)

    while True:
        already_names = _onboarded_display_names(registry)
        # Don't re-suggest towns already in the seed list
        all_known = list(set(seed_towns) | set(already_names))

        remaining = (
            batch_total - total_onboarded_this_session
            if batch_total else per_round
        )
        this_round = min(per_round, remaining) if batch_total else per_round

        if this_round <= 0:
            logger.info("expansion_agent | Batch target reached — exiting.")
            break

        # --- LLM call ---
        try:
            suggested = _ask_llm(
                seed_towns=seed_towns,
                already_onboarded=all_known,
                n=this_round,
                provider=effective_provider,
                model=effective_model,
            )
        except (RuntimeError, ValueError) as exc:
            logger.error("expansion_agent | LLM call failed: %s", exc)
            break

        # --- Scaffold + register ---
        round_results = []
        for town in suggested:
            slug = _make_slug(town["town_name"], town["state"])

            if slug in _onboarded_slugs(registry):
                logger.info("expansion_agent | %s already onboarded — skipping.", slug)
                continue

            config_path = _scaffold_config(
                town=town,
                seed_source=", ".join(seed_towns[:3]) + (" ..." if len(seed_towns) > 3 else ""),
                llm_model=effective_model,
                dry_run=dry_run,
            )

            entry = {
                "town_slug":  slug,
                "town_name":  town["town_name"],
                "state":      town["state"],
                "lat":        town.get("lat"),
                "lon":        town.get("lon"),
                "geo_hash":   _compute_geohash(float(town["lat"]), float(town["lon"])),
                "config_path": str(config_path),
                "rationale":  town.get("rationale", ""),
            }
            if not dry_run:
                registry["onboarded"].append(entry)
            round_results.append(entry)
            total_onboarded_this_session += 1

        # Persist registry
        if not dry_run:
            registry.setdefault("rounds", []).append({
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "model": effective_model,
                "added": [r["town_slug"] for r in round_results],
            })
            _save_registry(registry)

        # --- Summary ---
        print(f"\n{'═'*62}")
        print(f"  Round complete — {len(round_results)} town(s) {'(DRY-RUN) ' if dry_run else ''}onboarded this round")
        print(f"  Total this session : {total_onboarded_this_session}")
        print(f"  Total in registry  : {len(registry.get('onboarded', []))}")
        print(f"{'═'*62}")
        for r in round_results:
            geo = r.get("geo_hash", "?")
            print(f"  ✓  {r['town_slug']:<30}  geo_hash={geo}  [{r.get('rationale','')[:55]}]")
        print()

        if batch_total and total_onboarded_this_session >= batch_total:
            logger.info("expansion_agent | Batch target of %d reached.", batch_total)
            break

        # Interactive prompt
        if not batch_total:
            try:
                answer = input("Continue with the next round? [Y/n] ").strip().lower()
            except EOFError:
                # Non-interactive environment (e.g. piped input) — stop
                break
            if answer in ("n", "no"):
                break


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------

def _parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="expansion_agent",
        description="TownEye UMF — Autonomous Expansion Engine (Patch #175)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=textwrap.dedent("""
            Examples:
              # Interactive — ask for next 10, then prompt to continue
              python core/expansion_agent.py

              # Batch — onboard 50 towns and exit
              python core/expansion_agent.py --batch 50

              # Custom seed, Anthropic backend, dry-run
              python core/expansion_agent.py \\
                  --seed "Cambridge MA,Medford MA,Malden MA" \\
                  --provider anthropic \\
                  --dry-run

              # Gemini backend
              python core/expansion_agent.py \\
                  --provider gemini \\
                  --model gemini-2.5-pro
        """),
    )
    parser.add_argument(
        "--seed",
        type=str,
        default="Arlington MA,Somerville MA,Burlington MA,Lexington MA,Bedford MA",
        help="Comma-separated list of seed towns (default: 5 Arlington-adjacent MA towns)",
    )
    parser.add_argument(
        "--batch",
        type=int,
        default=None,
        metavar="N",
        help="Onboard N towns total and exit (non-interactive)",
    )
    parser.add_argument(
        "--per-round",
        type=int,
        default=10,
        metavar="N",
        help="Towns to request per LLM call (default: 10)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print scaffolded configs to stdout; do not write any files",
    )
    parser.add_argument(
        "--provider",
        choices=["gemini", "openai", "anthropic"],
        default=None,
        help=(
            "LLM backend (auto-detected from env vars when omitted). "
            "Priority: gemini > openai > anthropic."
        ),
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help=(
            "Override LLM model name "
            "(defaults: gemini-2.5-flash | gpt-4o-mini | claude-3-5-haiku-20250219)"
        ),
    )
    parser.add_argument(
        "--show-registry",
        action="store_true",
        help="Print the current expansion registry and exit",
    )
    return parser.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
        datefmt="%Y-%m-%dT%H:%M:%S",
        stream=sys.stdout,
    )

    args = _parse_args(argv)

    if args.show_registry:
        registry = _load_registry()
        print(json.dumps(registry, indent=2))
        return

    seed_towns = [t.strip() for t in args.seed.split(",") if t.strip()]

    run_expansion(
        seed_towns=seed_towns,
        batch_total=args.batch,
        per_round=args.per_round,
        dry_run=args.dry_run,
        provider=args.provider,
        model=args.model,
    )


if __name__ == "__main__":
    main()

# core/expansion_agent.py
# End of Patch #175
